"""
Idempotent .env management.

Behaviour:
  * If `.env` exists, leave it alone (never clobber user-managed secrets).
  * If `.env` is missing and `.env.example` exists, copy with
    `_dev_defaults_applied()` — placeholder API-keys flipped to
    obviously-fake values + dev-friendly DEBUG/LOG_LEVEL.
  * If neither exists, write a minimal-known-good seed.

Returns an `EnvFileResult` describing what happened so the caller can
report sensibly.

NO secrets are written by this module — the seed values are dev
placeholders; the user MUST supply real keys before exposing the
service to the internet.
"""

from __future__ import annotations

import re
import shutil
from dataclasses import dataclass
from pathlib import Path

from tools.setup import constants

# Keys whose example value contains a placeholder ("your-...-here") we
# rewrite to a clearly-fake dev value so the app boots without external
# keys.  The user is expected to override these for production.
_PLACEHOLDER_OVERRIDES: dict[str, str] = {
    "GOOGLE_TRANSLATE_API_KEY": "",
    "AZURE_TRANSLATOR_KEY": "",
    "AZURE_TRANSLATOR_ENDPOINT": "",
    "OPENAI_API_KEY": "",
    "ANTHROPIC_API_KEY": "",
    "DEBUG": "false",
    "LOG_LEVEL": "INFO",
}

# Minimal seed used if neither .env nor .env.example exists.  Stays
# in sync with docker-compose's expectations.
_MINIMAL_SEED = """\
# AMOR — minimal .env seed (generated by tools/setup).
# Override before exposing to the internet.

SERVICE_NAME=document-processor
ENVIRONMENT=development
LOG_LEVEL=INFO
DEBUG=false

POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_DATABASE=docdb
POSTGRES_USER=docuser
POSTGRES_PASSWORD=docpass123

MONGO_HOST=mongo
MONGO_PORT=27017
MONGO_DATABASE=documents
MONGO_USER=
MONGO_PASSWORD=

REDIS_HOST=redis
REDIS_PORT=6379
REDIS_DB=0
REDIS_PASSWORD=

KAFKA_BOOTSTRAP_SERVERS=kafka:9092
KAFKA_TOPIC=documents
KAFKA_GROUP_ID=processors
"""

_PLACEHOLDER_RE = re.compile(r"your-[a-z0-9-]*-here", re.IGNORECASE)


@dataclass
class EnvFileResult:
    """Describes what `ensure_env_file()` did."""

    path: Path
    action: str          # "kept" | "copied-example" | "seeded"
    overrides_applied: tuple[str, ...] = ()

    @property
    def created(self) -> bool:
        return self.action != "kept"


def _apply_dev_overrides(text: str) -> tuple[str, list[str]]:
    """Patch placeholder values to safe-empty dev defaults.

    Returns (new_text, list_of_keys_changed).
    """

    out_lines: list[str] = []
    changed: list[str] = []
    for raw in text.splitlines():
        line = raw
        m = re.match(r"^([A-Z][A-Z0-9_]+)\s*=\s*(.*)$", line)
        if m:
            key = m.group(1)
            val = m.group(2)
            if key in _PLACEHOLDER_OVERRIDES:
                new_val = _PLACEHOLDER_OVERRIDES[key]
                if val != new_val:
                    line = f"{key}={new_val}"
                    changed.append(key)
            elif _PLACEHOLDER_RE.search(val):
                # Generic "your-...-here" placeholder — wipe it.
                line = f"{key}="
                changed.append(key)
        out_lines.append(line)
    return ("\n".join(out_lines) + ("\n" if not text.endswith("\n") else ""), changed)


def ensure_env_file(
    *,
    repo_root: Path | None = None,
) -> EnvFileResult:
    """Idempotently materialize .env in repo root."""

    if repo_root is None:
        repo_root = constants.REPO_ROOT
    env_path = repo_root / ".env"
    example_path = repo_root / ".env.example"

    if env_path.exists():
        return EnvFileResult(path=env_path, action="kept")

    if example_path.exists():
        text = example_path.read_text(encoding="utf-8")
        patched, changed = _apply_dev_overrides(text)
        env_path.write_text(patched, encoding="utf-8")
        return EnvFileResult(
            path=env_path,
            action="copied-example",
            overrides_applied=tuple(changed),
        )

    env_path.write_text(_MINIMAL_SEED, encoding="utf-8")
    return EnvFileResult(path=env_path, action="seeded")


def read_env(path: Path | None = None) -> dict[str, str]:
    """Parse a .env file into a dict.  Quoting/escaping kept simple."""

    if path is None:
        path = constants.REPO_ROOT / ".env"
    out: dict[str, str] = {}
    if not path.exists():
        return out
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, val = line.partition("=")
        key = key.strip()
        val = val.strip().strip('"').strip("'")
        out[key] = val
    return out


def ensure_data_dirs(*, repo_root: Path | None = None) -> list[Path]:
    """Create the host-side data directories that compose bind-mounts.

    Returns the paths that were created (empty list = nothing new).
    """

    if repo_root is None:
        repo_root = constants.REPO_ROOT
    targets = [
        repo_root / "data",
        repo_root / "data" / "baselines",
        repo_root / "data" / "setup_logs",
        repo_root / "data" / "amor_memory",
        repo_root / "models",
        repo_root / "sandbox-shared",
    ]
    created: list[Path] = []
    for path in targets:
        if not path.exists():
            path.mkdir(parents=True, exist_ok=True)
            created.append(path)
    return created
